module.exports = {
  apps: [
    {
      name: 'edufy-super-admin',
      cwd: './apps/super-admin',
      script: 'npm',
      args: 'start',
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 7000,
      },
      env_file: './apps/super-admin/.env.local',
      error_file: './logs/super-admin-error.log',
      out_file: './logs/super-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'edufy-parent-portal',
      cwd: './apps/parent-portal',
      script: 'npm',
      args: 'start',
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 7001,
      },
      env_file: './apps/parent-portal/.env.local',
      error_file: './logs/parent-portal-error.log',
      out_file: './logs/parent-portal-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'edufy-transport-admin',
      cwd: './apps/transport-admin',
      script: 'npm',
      args: 'start',
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 7002,
      },
      env_file: './apps/transport-admin/.env.local',
      error_file: './logs/transport-admin-error.log',
      out_file: './logs/transport-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'edufy-payroll-admin',
      cwd: './apps/payroll-admin',
      script: 'npm',
      args: 'start',
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 7003,
      },
      env_file: './apps/payroll-admin/.env.local',
      error_file: './logs/payroll-admin-error.log',
      out_file: './logs/payroll-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'edufy-inventory-admin',
      cwd: './apps/inventory-admin',
      script: 'npm',
      args: 'start',
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 7004,
      },
      env_file: './apps/inventory-admin/.env.local',
      error_file: './logs/inventory-admin-error.log',
      out_file: './logs/inventory-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
}
